public class ReportCalculations {
	
    public static List<Map<String, Object>> traineeAverage(List<Map<String, Object>> trainees){
        
        return null;
    }
    
    public static Decimal benchmark(List<Map<String, Object>> allGrades){
        
        return null;
    }
    
    public static List<Map<String, Object>> categoryAverage(List<Map<String, Object>> categories){
        
        return null;
    }
}